entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      redirections:
        entryPoint:
          to: ocis
          scheme: https
  ocis:
    address: ":9200"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: ocisnet
