[http]
  [http.routers]
    [http.routers.http-to-ocis]
      rule = "Host(`ocis.local`)"
      service = "ocis"
      entrypoints = ["http"]
      middlewares = ["redirect"]

    [http.routers.https-to-ocis]
      rule = "Host(`ocis.local`)"
      service = "ocis"
      entrypoints = ["https"]
      [http.routers.https-to-ocis.tls]

    [http.routers.http-to-oc10]
      rule = "Host(`oc10.local`)"
      service = "oc10"
      entrypoints = ["http"]
      middlewares = ["redirect"]

    [http.routers.https-to-oc10]
      rule = "Host(`oc10.local`)"
      service = "oc10"
      entrypoints = ["https"]
      [http.routers.https-to-oc10.tls]

  [http.services]
    [http.services.ocis]
      [http.services.ocis.loadBalancer]
       passHostHeader = true

        [[http.services.ocis.loadBalancer.servers]]
          # This is where your dev app lives.
          url = "http://ocis:9200"

    [http.services.oc10]
      [http.services.oc10.loadBalancer]
       passHostHeader = true

        [[http.services.oc10.loadBalancer.servers]]
          # This is where your dev app lives.
          url = "http://oc10:8080"

  [http.middlewares]
    [http.middlewares.redirect.redirectScheme]
      scheme = "https"

[tls]
  [[tls.certificates]]
