[global]
  sendAnonymousUsage = false

[log]
  # If something goes wrong, changing this to `DEBUG` might help you finding
  # out what happens.
  level = "DEBUG" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

[providers]
  [providers.file]
    filename = "/etc/traefik/traefik.config.toml"
    watch = true

[api]
  insecure = true
  dashboard = true