---
version: '3.4'

services:
    grafana:
      image: grafana/grafana:5.1.0
      ports:
        - 3000:3000
      volumes:
        - ../metrics/provisioning/:/etc/grafana/provisioning/
        - ../metrics/plugins/:/var/lib/grafana/plugins/
        - ../metrics/dashboards/:/var/lib/grafana/dashboards/